---
deployment:
  tasks:
    - export DEPLOYPATH=/home2/hg3ads37/experiencia.haikar.com.br/
    - /bin/mkdir -p "$DEPLOYPATH"
    - if [ "$PWD" != "${DEPLOYPATH%/}" ]; then /bin/cp -f index.html "$DEPLOYPATH"; fi
